language: go
sudo: false
go:
    - tip
before_install:
    - go get github.com/mattn/goveralls
    - go get golang.org/x/tools/cmd/cover
before_script:
    - go fmt ./...
    - go vet ./...
script:
    - $HOME/gopath/bin/goveralls -service=travis-ci
